Repository jenkinsci/ui-ux-hackfest-2020, pull requests merged in 2020-05, with the labels that each got.

#20 Create CODEOWNERS
  CODEOWNERS
Labels: chore

#25 Add AutoLabeler configuration
  .github/autolabeler.yml
Labels: chore

#24 Update the welcome bot template
  .github/config.yml
Labels: chore

#27 Contributing - Extend the issue reporting guidelines
  CONTRIBUTING.md
Labels: documentation

#28 README: Shorten resources, reference more content
  README.md
Labels: documentation

#32 Fix a link for @oleg-nenashev
  .all-contributorsrc
Labels: all-contributors

#31 Add Issue template for reviews
  .github/ISSUE_TEMPLATE/6-reviews.md
Labels: chore, documentation

#49 Enable alphabetical sorting, sponsoring organizations from the contributors list
  .all-contributorsrc
  README.md
Labels: all-contributors, documentation

#45 Create ORGANIZERS.md
  ORGANIZERS.md
Labels: chore, documentation

#63 Allow reporting UX Testing issues right inside the repo
  .github/ISSUE_TEMPLATE/5-ux-testing.md
Labels: chore, documentation

#64 Typo
  README.md
Labels: documentation

#69 Add listing of the previous knowledge transfer sessions
  README.md
  presentations/01-kickoff/README.md
  presentations/01-kickoff/slides.pdf
  presentations/02-beautify-plugin-ui/README.md
  presentations/03-jenkins-is-the-way-intro/README.md
  presentations/03-jenkins-is-the-way-intro/slides.pdf
  presentations/04-migrating-plugin-docs/README.md
  presentations/README.md
Labels: documentation, spread-the-word

#102 Add Tuesday sessions
  presentations/03-jenkins-is-the-way-intro/README.md
  presentations/05-system-read/README.md
  presentations/05-system-read/slides.pdf
  presentations/06-migrating-docs/README.md
  presentations/06-migrating-docs/slides.pdf
Labels: documentation

#163 Add Spread The Word contribution type
  .all-contributorsrc
Labels: all-contributors

#199 Add recording and materials for the Hackfest demos session
  presentations/09-demo-sessions/README.md
  presentations/09-demo-sessions/opening_slides.pdf
Labels: documentation
